

#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 05 - Al-Maweri 13
#+AUTHOR: Daniel Geinets (453843), Christopher Neumann (409098), Dennis Schulze (458415)

#+LATEX_CLASS_OPTIONS: [a4paper, 11pt]

#+LATEX_HEADER: \usepackage{braket}
#+LATEX_HEADER: \usepackage[AUTO]{babel}

#+LANGUAGE: de

#+LATEX: \setcounter{secnumdepth}{0}
#+LATEX: \newcommand{\tuple}[1]{\left(#1\right)}
#+LATEX: \renewcommand{\cfrac}[3]{#1 \tuple{\frac{#2}{#3}}}
#+LATEX: \newcommand{\R}{\mathbb{R}}
#+LATEX: \newcommand{\Z}{\mathbb{Z}}
#+LATEX: \newcommand{\Q}{\mathbb{Q}}
#+LATEX: \newcommand{\N}{\mathbb{N}}
#+LATEX: \newcommand{\C}{\mathbb{C}}

#+LATEX: \makeatletter
#+LATEX: \renewcommand*\env@matrix[1][*\c@MaxMatrixCols c]{%
#+LATEX:   \hskip -\arraycolsep
#+LATEX:   \let\@ifnextchar\new@ifnextchar
#+LATEX:   \array{#1}}
#+LATEX: \makeatother

\pagebreak

* Aufgabe 1
** a)

** b)

** c)

** d)

* Aufgabe 2
** a)
Da $f$ linear ist gelten $f(x+y) = f(x) + f(y)$ und
$f(r \cdot x) = r \cdot f(x)$. Damit gilt

\begin{align*}
    f(2x) &= 2f(x + 3) - 6 f(1) \\
    &= 2(-2x + 1) - 6(x + 2) \\
    &= -4x + 2 - 6x - 12 \\
    &= -10x - 10
\end{align*}

** b)
\begin{align*}
    f(1) &= x + 2 \\
    f(x) &= -5x -5
\end{align*}

Seien $a, b \in \R$, dann gilt

\begin{align*}
    f(ax + b) &= f(ax) + f(b) = a f(x) + b f(1) \\
    &= a(-5x - 5) + b(x + 2) \\
    &= -5ax - 5a + bx + 2b \\
    &= (b - 5a)x + (2b - 5a)
\end{align*}

also gilt

$$ f: \begin{bmatrix} a \\ b \end{bmatrix} \mapsto
    \begin{bmatrix} b - 5a \\ 2b - 5a \end{bmatrix} $$

$f$ lässt als Matrix wie folgt darstellen

$$ f = \begin{bmatrix} -5 & 1 \\ -5 & 2 \end{bmatrix} $$

linear abhängig? mit $r_1, r_2 \in \R$

$$ \begin{bmatrix} 0 \\ 0 \end{bmatrix} =
    r_1 \begin{bmatrix} a \\ b \end{bmatrix} +
    r_2 \begin{bmatrix} a \\ b \end{bmatrix} $$

daraus ergibt sich ein LGS, dass zu einem Widerspruch führt

\begin{align*}
    \text{(I) } 0 &= r_2 - 5r_1 \\
    \text{(II) } 0 &= 2r_2 - 5r_1 \\
\end{align*}

daraus folgt, dass die Spalten linear unabhängig sind, Woraus folgt

$$ \dim(\text{Bild}(f)) = 2 $$

** c)
Überführen der Matrix

\begin{align*}
    \begin{bmatrix}[cc|c]
        -5 & 1 & 0 \\
        -5 & 2 & 0
    \end{bmatrix}
    &\xrightarrow{\text{II} - \text{I}}
    \begin{bmatrix}[cc|c]
        -5 & 1 & 0 \\
        0 & 1 & 0
    \end{bmatrix} \\
    \xrightarrow{\text{I} - \text{II}}
    \begin{bmatrix}[cc|c]
        -5 & 0 & 0 \\
        0 & 1 & 0
    \end{bmatrix}
    &\xrightarrow{ \frac{-1}{5}\text{I}}
    \begin{bmatrix}[cc|c]
        1 & 0 & 0 \\
        0 & 1 & 0
    \end{bmatrix}
\end{align*}

Für Kern($f$) gibt es also nur eine Lösung

$$ \text{Kern}(f) = \left\{ \begin{bmatrix} 0 \\ 0 \end{bmatrix} \right\} $$

daraus folgt

$$ B_{\text{Kern}(f)} = \{\} $$

** d)

* Aufgabe 3
Es gilt

$$ (3k + 1)(3k + 4) =
    9 \tuple{k + \frac{1}{3}} \tuple{k + \frac{4}{3}} $$

daraus ergibt sich dann der folgende Ansatz

$$ \frac{3}{(3k + 1)(3k + 4)} =
    \frac{A}{k + \frac{1}{3}} +
    \frac{B}{k + \frac{4}{3}} $$

für $A$ mit $k = -\frac{1}{3}$

$$ \frac{1}{3} \cdot \frac{1}{-\frac{1}{3} + \frac{4}{3}} = A = \frac{1}{3} $$

und für $B$ mit $k = -\frac{4}{3}$

$$ \frac{1}{3} \cdot \frac{1}{-\frac{4}{3} + \frac{1}{3}} = A = -\frac{1}{3} $$

daraus folgt

\begin{align*}
    \sum_{k = 0}^{n} \frac{3}{(3k + 1)(3k + 4)} &=
        \sum_{k = 0}^{n} \tuple{ \frac{1}{3(k + \frac{1}{3})} -
            \frac{1}{3(k + \frac{4}{3})} } \\
    &= \sum_{k = 0}^{n} \tuple{ \frac{1}{3k + 1} - \frac{1}{3k + 4} } \\
    &= \tuple{\frac{1}{1} - \frac{1}{4}} +
        \tuple{\frac{1}{4} - \frac{1}{7}} +
        \tuple{\frac{1}{7} - \frac{1}{10}} + \dots + \\
       & \tuple{ \frac{1}{3n - 2} - \frac{1}{3n + 1} } +
        \tuple{ \frac{1}{3n + 1} - \frac{1}{3n + 4} } \\
    &= 1 + \frac{1}{3n + 4}
\end{align*}

* Aufgabe 4
** a)
IA: Es gilt

$$ x_0 = 1 < \frac{4}{3} $$

IV: Es gelte für ein beliebiges $n \in \N$

$$ x_n < \frac{4}{3} $$

IB: Damit gilt dann

$$ x_{n+1} < \frac{4}{3} $$

IS: Es gilt

\begin{align*}
    x_{n+1} &< \frac{4}{3} \\
    \Leftrightarrow \frac{x_n}{4} + 1 &< \frac{4}{3} \\
    \Leftrightarrow \frac{x_n}{4} &< \frac{1}{3} \\
    \Leftrightarrow x_n &< \frac{4}{3} \\
\end{align*}

Folglich gilt dann für alle $n \in \N$

$$ x_n < \frac{4}{3} $$

** b)
Es gelte $x_n < x_{n+1}$. \\
Dann gilt

\begin{align*}
    x_n &< x_{n+1} \\
    \Leftrightarrow \frac{x_{n-1}}{4} + 1 &< \frac{x_n}{4} + 1 \\
    \Leftrightarrow \frac{x_{n-1}}{4} &< \frac{x_n}{4} \\
    \Leftrightarrow x_{n-1} &< x_n \\
\end{align*}

Diese Umformung kann $k$-mal wiederholt werden bis $k = n$ gilt. \\
Daraus folgt dann, dass die Folge $x_n$ streng monoton wachsend.

** c)
Die Folge $x_n$ ist nach oben beschränkt mit $M = \frac{4}{3}$ (siehe a) \\
\\
Die Folge $x_n$ ist streng monoton wachsend (siehe b) \\
\\
Daraus folgt die Folge $x_n$ konvergiert.

** d)
Es gilt für die ersten Folgeglieder

\begin{align*}
    x_0 &= 1 \\
    x_1 &= \frac{x_0}{4} + 1 = \frac{1}{4} + 1 \\
    x_2 &= \frac{x_1}{4} + 1 = \frac{1}{16} + \frac{1}{4} + 1 \\
    \vdots
\end{align*}

Man kann die Folge also auch wie folgt schreiben

$$ x_n = \sum_{k = 0}^{n} \frac{1}{4^k} $$

dann gilt

\begin{align*}
    x_n &= \sum_{k = 0}^{n} \frac{1}{4^k}
    = \sum_{k = 0}^{n} \tuple{\frac{1}{4}}^k \\
    &= \frac{1 - \tuple{\frac{1}{4}}^{n+1}}{1 - \frac{1}{4}}
    = \frac{4 - \tuple{\frac{1}{4}}^n}{3}
\end{align*}

dann gilt für den Grenzwert

\begin{align*}
    \lim_{n \rightarrow \infty} \frac{4 - \tuple{\frac{1}{4}}^n}{3} &=
        \lim_{n \rightarrow \infty} \frac{4}{3} -
        \lim_{n \rightarrow \infty} \frac{\tuple{\frac{1}{4}}^n}{3} \\
    &= \frac{4}{3} - \lim_{n \rightarrow \infty} \frac{1}{3 \cdot 4^n} \\
    &= \frac{4}{3} - 0 = \frac{4}{3}
\end{align*}
