

#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 09 - Al-Maweri 13
#+AUTHOR: Daniel Geinets (453843), Christopher Neumann (409098), Dennis Schulze (458415)

#+LATEX_CLASS_OPTIONS: [a4paper, 11pt]

#+LATEX_HEADER: \usepackage{braket}
#+LATEX_HEADER: \usepackage[AUTO]{babel}
#+LATEX_HEADER: \usepackage[dvipsnames]{xcolor}

#+LATEX_HEADER: \definecolor{BG}{RGB}{28, 20, 8}
#+LATEX_HEADER: \definecolor{FG}{RGB}{60, 140, 0}

#+LATEX_HEADER: \pagecolor{BG}
#+LATEX_HEADER: \color{FG}

#+LANGUAGE: de

#+LATEX: \setcounter{secnumdepth}{0}
#+LATEX: \newcommand{\tuple}[1]{\left(#1\right)}
#+LATEX: \newcommand{\R}{\mathbb{R}}
#+LATEX: \newcommand{\Z}{\mathbb{Z}}
#+LATEX: \newcommand{\Q}{\mathbb{Q}}
#+LATEX: \newcommand{\N}{\mathbb{N}}
#+LATEX: \newcommand{\C}{\mathbb{C}}

#+LATEX: \makeatletter
#+LATEX: \renewcommand*\env@matrix[1][*\c@MaxMatrixCols c]{%
#+LATEX:   \hskip -\arraycolsep
#+LATEX:   \let\@ifnextchar\new@ifnextchar
#+LATEX:   \array{#1}}
#+LATEX: \makeatother

\pagebreak

* Aufgabe 1
** a)
Es gilt

\begin{align*}
    f(x) &= \ln(x) \\
    f'(x) &= \frac{1}{x} = x^{-1} \\
    f''(x) &= -\frac{1}{x^2} = -x^{-2} \\
    f'''(x) &= \frac{2}{x^3} = x^{-1} \\
\end{align*}

dann gilt für die Taylorpoynome T_1 und T_2

\begin{align*}
    T_1(x) &= f(x_0) + f'(x_0)(x - x_0) \\
    &= 0 + 1 \cdot (x - 1) = x - 1 \\
    T_2(x) &= f(x_0) + f'(x_0)(x - x_0) + \frac{f''(x_0)}{2!}(x - x_0)^2 \\
    &= 0 + 1 \cdot (x - 1) + \frac{-1}{2}(x - 1)^2
        = x - 1 - \frac{(x - 1)^2}{2}
\end{align*}

für dessen Restglieder gilt

\begin{align*}
    R_1(x) &= \frac{f''(\xi)(x-1)^2}{2!} \\
        &= \frac{1}{2} \cdot \frac{-1}{\xi^2} (x - 1)^2
        = \frac{-(x - 1)^2}{2 \xi^2} \\
    R_2(x) &= \frac{f'''(\xi)(x-1)^3}{3!} \\
        &= \frac{1}{6} \cdot \frac{2}{\xi^3} (x - 1)^3
        = \frac{(x - 1)^3}{3 \xi^3}
\end{align*}

dann gilt

\begin{equation*}
    \ln(x) = T_1(x) + R_1(x) \text{ bzw. } \ln(x) = T_2(x) + R_2(x)
\end{equation*}

Damit die Ungleichungen $\ln(x) < T_1(x)$ und $\ln(x) > T_2(x)$ gelten,
müssen die folgenden Ungleichungen erfüllt sein.

\begin{equation*}
    0 > R_1(x) \text{ und } 0 < R_2(x)
\end{equation*}

der Nenner der Restglieder ist immer größer 0 für alle $\xi \in ]x_0, x[$
dann gilt

\begin{align*}
    x - 1 &> 0, \forall x \in ]1, \infty[ \\
    \Rightarrow (x-1)^2 &> 0 \text{ bzw. } (x-1)^3 > 0, \forall x \in ]1, \infty[ \\
    \Rightarrow -(x-1)^2 &< 0, \forall x \in ]1, \infty[ \\
    \Rightarrow 0 &> R_1(x) \text{ bzw. } 0 < R_2(x), \forall x \in ]1, \infty[
\end{align*}

somit gilt

$$ x-1-\frac{(x-1)^2}{2} < \ln x < x - 1 $$

** b)
_Für das Monotoniekriterium:_ \newline

\begin{math}
x-1-\frac{(x-1)^2}{2} < \ln x \text{ , da:}
\newline
\newline
(x-1-\frac{(x-1)^2}{2})' = 2-x < 0 \text{ , für } x \in ]2, \infty[ \Rightarrow \text{ streng monoton fallend}
\newline
\newline
(\ln x)' = \frac{1}{x} > 0 \text{ , für } x \in ]1, \infty[ \Rightarrow \text{ streng monoton steigend}
\newline
\newline
\text{Somit: }
\end{math}
	\begin{align*}
		\lim \limits_{x \to \infty}\left( x-1-\frac{(x-1)^2}{2}\right) &\overset{\text{GWS}}{=} -\infty \\
		\lim \limits_{x \to \infty}(\ln x) &\overset{\text{GWS}}{=} \infty \\
		\Rightarrow x-1-\frac{(x-1)^2}{2} &< \ln x \text{ , für } x \in ]1, \infty[
	\end{align*}

_Für den Mittelwertsatz:_ \newline

Zu zeigen ist, dass \ln(x)< x-1 für alle x \in  ]1,$\infty$[
\newline
\newline
$f(x) = \ln(x)$,  $a$ = 1, b = x, \xi  \in  ]1,$\infty$[
\newline
\newline
$\frac{\ln(x)-\ln(1)}{x-1}$ = $\frac{f(x)-f(1)}{x-1}$ = $f'(\xi)$ = (ln(\xi))' = $\frac{1}{\xi}$ \Leftrightarrow
\newline
\newline
$\frac{\ln(x)}{x-1}$ = $\frac{1}{\xi}$
\newline
\newline
\Leftrightarrow ln($x$) = $\frac{1}{\xi}$ ($x-1$)
\newline
\newline
$\frac{1}{\xi}$ < 1, \text{ da } \xi \in  ]1,$\infty$[ gilt \xi > 1  und  damit
$\frac{1}{\xi}$ < 1
\newline
\newline
ln($x$) < $x-1$ \text{ für alle } $x$ \in  ]1,$\infty$[

* Aufgabe 2
Es gilt

\begin{align*}
    f(x)    &= 3^x = e^{x \ln(3)} = (\ln(3))^0 e^{x \ln(3)} \\
    f'(x)   &= \ln(3) e^{x \ln(3)} = (\ln(3))^1 e^{x \ln(3)} \\
    f''(x)  &= (\ln(3))^2 e^{x \ln(3)} \\
    f'''(x) &= (\ln(3))^3 e^{x \ln(3)} \\
    &\vdots \\
    f^{(n)}(x) &= (\ln(3))^n e^{x \ln(3)}
\end{align*}

dann gilt für das Taylorpolynom T_n

\begin{align*}
    T_n(x) &= f(x_0) + \frac{f'(x_0)}{1!}x + \frac{f''(x_0)}{2!}x^2 + \dots + \frac{f(x_0)}{n!}x^n \\
    &= 1 + \ln(3)x + \frac{(\ln(3))^2}{2}x^2 + \frac{(\ln(3))^3}{6}x^3 + \dots + \frac{(\ln(3))^n}{n!}x^n \\
    &= \sum_{k = 0}^{n} \frac{(\ln(3))^k x^k}{k!}
\end{align*}

und es gilt für das Restglied R_n

\begin{equation*}
    R_n(x) = \frac{f^{(n+1)}(\xi)}{(n+1)!}x^{n+1}
        = \frac{ (\ln(3))^{n+1} e^{\ln(3)\xi}}{(n+1)!}x^{n+1}
        = \frac{ (\ln(3))^{n+1} x^{n+1}}{(n+1)!} e^{\ln(3)\xi}
\end{equation*}

Betrachtet man das Restglied nun als Folge mit einem festen $x \in ]1, \infty[$
und da dann das $n$ gegen $\infty$ konvergieren als, fällt auf, dass irgendeine
Exponentialfunktion durch die "Fakultätsfunktion" geteilt wird. Da die "Fakultätsfunktion" wächst
schneller als jede Exponentialfunktion, müsste gelten

\begin{equation*}
    \lim_{n \leftarrow \infty} R_n(x) = 0, \forall x \in \R
\end{equation*}

* Aufgabe 3
** a)
Für $x,y > 0, x,y \in \R$ gilt:

\begin{align*}
    0 &\leq (x-y)^2 \\
    \Leftrightarrow 0 &\leq x^2 -2xy+y^2 \\
    \Leftrightarrow 4xy &\leq x^2 + 2xy + y^2 \\
    \Leftrightarrow xy &\leq \frac{x^2+2xy+y^2}{4} = \frac{(x+y)^2}{4} \\
    \Leftrightarrow (xy)^{\frac{1}{2}} &\leq \frac{x+y}{2} \\
    \Leftrightarrow \ln((xy)^{\frac{1}{2}}) &\leq \ln\left(\frac{x+y}{2}\right) \\
    \Leftrightarrow \frac{\ln(xy)}{2} = \frac{\ln(x) + \ln(y)}{2} &\leq \ln\left(\frac{x+y}{2}\right)
\end{align*}

** b)
\begin{math}
\operatorname{artanh} x = \frac{1}{2}\ln\left(\frac{1+x}{1-x}\right) \text{ , für alle }x \in ]-1,1[
\newline
\end{math}
	\begin{align*}
		y = \operatorname{artanh} x &= \tanh^{-1}x \\
		\tanh^{-1}x &= y \\
		\Leftrightarrow \tanh(\tanh^{-1}x) &= \tanh y \\
		\Leftrightarrow x &= \tanh y = \frac{\sinh y}{\cosh y} = \frac{e^y - e^{-y}}{e^y + e^{-y}} \\
		\Leftrightarrow x &= \frac{e^{2y} - 1}{e^{2y} + 1} \\
		\Leftrightarrow e^{2y}-1 &= xe^{2y} + x \\
		\Leftrightarrow (1-x)e^{2y} &= x+1 \\
		\Leftrightarrow e^{2y} &= \frac{x+1}{x-1} \\
		\Leftrightarrow 2y &= \ln \left(\frac{1+x}{1-x}\right) \\
		\Leftrightarrow y &= \frac{1}{2} \ln \left(\frac{1+x}{1-x}\right) \\
	\end{align*}
\begin{math}
\Rightarrow \operatorname{artanh} x = \frac{1}{2} \ln \left(\frac{1+x}{1-x}\right) \text{ , für } -1 < x < 1
\end{math}
