
#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 03
#+AUTHOR: Moaz Haque, Felix Oechelhaeuser, Leo Pirker, Dennis Schulze

* Aufgabe 1
** a)
*** z_1
$$
  z_1 = 4e^{-\frac{\pi}{6}i}
  = 4(\cos(-\frac{\pi}{6}) + i\sin(-\frac{\pi}{6}))
  = 4(\frac{\sqrt{3}}{2} - \frac{1}{2}i)
$$
$$= 2\sqrt{3} - 2i$$

*** z_2
$$
  z_2 = 2e^{\frac{16}{3}\pi i}
  = 2e^{(\frac{4}{3} + 4)\pi i}
  = 2e^{\frac{4}{3}\pi i}
  = -2e^{\frac{1}{3}\pi i}
$$
$$= -2(\cos(\frac{\pi}{3}) + i\sin(\frac{\pi}{3}))$$
$$
  = -2(\frac{\sqrt{2}}{2} + \frac{\sqrt{2}}{2}i)
  = -\sqrt{2} - \sqrt{2}i
$$

** b)
*** z_1
$$r^2 = (-3)^2 + (-3)^2 = 18$$
$$\tan(\phi) = \frac{-3}{-3}$$
Der Nenner ist kleiner als 0:
$$
  \Rightarrow \phi = \arctan(\frac{-3}{-3}) + \pi
  = \frac{\pi}{4} + \pi = \frac{5\pi}{4}
$$
Damit ist z_1 in Eulerdarstellung:
$$z_1 = \sqrt{18}e^{\frac{5\pi}{4}i}$$

*** z_2
$$r^2 = 2^2 + (\sqrt{12})^2 = 4 + 12 = 16$$
$$\Leftrightarrow r = 4$$

$$\tan(\phi) = \frac{\sqrt{12}}{2}$$
Der Nenner ist größer 0:
$$\Rightarrow \phi = \arctan(\frac{\sqrt{12}}{2}) = \frac{\pi}{3}$$
Damit ist z_2 in Eulerdarstellung:
$$z_2 = 4e^{\frac{\pi}{3}i}$$

* Aufgabe 2
** a)
$$z^3 + \sqrt{2} - \sqrt{2}i = 0$$
$$\Leftrightarrow z^3 + 2e^{\frac{-\pi}{4}i} = 0$$
$$\Leftrightarrow z^3 = -2e^{\frac{-\pi}{4}i}$$
$$\Leftrightarrow z = \sqrt[3]{-2}e^{\frac{-\pi}{12}i} = z_1$$
Die anderen Lösungen z_2 und z_3 lassen sich finden, wenn man den Term $\frac{2k\pi}{3}$ mit k \in {1, 2}
hinzu addiert. Somit erhält man:
$$z_k = \sqrt[3]{-2}e^{(\frac{-\pi}{12} + \frac{2k\pi}{3})i}, k \in {0, 1, 2}$$
$$\Leftrightarrow z_k = \sqrt[3]{-2}e^{(\frac{-\pi}{12} + \frac{8k\pi}{12})i}$$
$$\Leftrightarrow z_k = \sqrt[3]{-2}e^{\frac{(8k - 1)\pi}{12}i}$$

** b)
$$z^5 = \frac{1 + i}{1 - i} \Leftrightarrow z^5 = \frac{(1 + i)^2}{2}$$
$$\Leftrightarrow z^5 = \frac{2i}{2} \Leftrightarrow z^5 = i$$
$$\Leftrightarrow z^5 = e^{\frac{\pi}{2}i}$$
$$\Leftrightarrow z = e^{\frac{\pi}{10}i}$$
Analog zu 2a) erhält man die anderen Lösungen mit den Term $\frac{2k\pi}{5}$ mit k \in {1, 2, 3, 4}.
Womit man erhält:
$$z_k = e^{(\frac{\pi}{10} + \frac{2k\pi}{5})i}, k \in {0, 1, 2, 3, 4}$$
$$\Leftrightarrow z_k = e^{(\frac{\pi}{10} + \frac{4k\pi}{10})i}$$
$$\Leftrightarrow z_k = e^{\frac{(1 + 4k)\pi}{10}i}$$

* Aufgabe 3
** a)
$$\deg(p(z)) = 4$$
Die Nullstellen von p sind {4, $i$, -5}, wobei $z_2 = i$ eine zwei-fache Nullstelle ist.

** b)
$$p(z) = \frac{z^5 + 4z^4 - 3z^3 + 2z^2 - z + 1}{z^2 - 3}$$

Die folgenden "Gleichungen" sind nicht als solche zu betrachten.
Sie zeigen lediglich die einzelnen Schritte der Polynomdivision.

$$(z^5 + 4z^4 - 3z^3 + 2z^2 - z + 1) / (z^2 - 3) = 0$$
$$(4z^4 - 6z^3 + 2z^2 - z + 1) / (z^2 - 3) = z^3$$
$$(-6z^3 - 10z^2 - z + 1) / (z^2 - 3) = z^3 + 4z^2$$
$$(-10z^2 + 17z + 1) / (z^2 - 3) = z^3 + 4z^2 - 6z$$
$$(17z + 31) / (z^2 - 3) = z^3 + 4z^2 - 6z - 10$$

Das Polynom nach der Division:

$$p(z) = z^3 + 4z^2 - 6z - 10 + \frac{17z + 31}{z^2 - 3}$$

* Aufgabe 4
** a)
$$p(2i) = (2i)^4 + (2i)^3 + 2(2i)^2 + 4(2i) - 8$$
$$= 16 - 8i - 8 + 8i - 8$$
$$= 0$$

** b)
$$\frac{p(z)}{q(z)} = \frac{z^4 + z^3 + 2z^2 + 4z - 8}{z^2 + 4}$$

Wie in 3b) sind die "Gleichungen" nur repräsentativ für den Schritt, der gerade durchgeführt wird.

$$(z^4 + z^3 + 2z^2 + 4z - 8) / (z^2 + 4) = 0$$
$$(z^3 - 2z^2 + 4z - 8) / (z^2 + 4) = z^2$$
$$(-2z^2 - 8) / (z^2 + 4) = z^2 + z$$
$$(0) / (z^2 + 4) = z^2 + z - 2$$

Das Polynom ist dann nach der Division:

$$\frac{p(z)}{q(z)} = z^2 + z - 2$$

** c)

* Aufgabe 5
** a)

** b)

* Aufgabe 6
** a)

** b)
