
#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 07 - Geuter 29
#+AUTHOR: Moaz Haque, Felix Oechelhaeuser, Leo Pirker, Dennis Schulze

#+LATEX_CLASS_OPTIONS: [a4paper,11pt]

#+LATEX_HEADER: \usepackage{pgfplots}

\pagebreak

* Aufgabe 1
** a)
Es gilt

\begin{align*}
  \frac{1}{b} + \frac{1}{g} &= \frac{1}{f} \\
  \Leftrightarrow \frac{1}{b} &= \frac{g - f}{fg} \\
  \Leftrightarrow b &= \frac{fg}{g - f}
\end{align*}

Damit ist b betrachtet als Funktion

$$ b(g) = \frac{fg}{g - f} $$

** b)
Da der Bruch nur für alle $g \neq f$ definiert ist, \\
ist b nur auf $\mathbb{R}$ \ {$f$} stetig.

** c)
Es gilt für den ersten Term

\begin{align*}
  \lim_{g \rightarrow \infty} b(g) &= \lim_{g \rightarrow \infty} \frac{fg}{g - f} \\
  &= \lim_{g \rightarrow \infty} \frac{f}{1 - \frac{f}{g}} \\
  &= \frac{f}{1 - 0} \\
  &= f
\end{align*}

Es gilt für den zweiten Term

\begin{align*}
  \lim_{g \rightarrow f} b(g) &= \lim_{g \rightarrow f} \frac{fg}{g - f} \\
  &= \frac{\lim_{g \rightarrow f} fg}{\lim_{g \rightarrow f} (g - f)} \\
  &= \frac{f^2}{f - f} \\
  &\Rightarrow \lim_{g \rightarrow f} b(g) = \infty
\end{align*}

* Aufgabe 2
** a)
Es gilt für $\lim_{x \rightarrow 1^-} f(x)$

\begin{align*}
  \lim_{x \rightarrow 1^-} f(x) &= \lim_{x \rightarrow 1^-} (\cos(\pi x) + 3) \\
  &= \cos(\pi) + 3 = -1 + 3 = 2
\end{align*}

und es gilt für $\lim_{x \rightarrow 1^+} f(x)$

\begin{align*}
  \lim_{x \rightarrow 1^+} f(x) &= \lim_{x \rightarrow 1^+} \frac{x^2 + 1}{x + 1} \\
  &= \frac{1^2 + 1}{1 + 1} = \frac{2}{2} = 1
\end{align*}

daraus folgt, dass $f$ an der Stelle $x = 1$ nicht stetig ist. \\

... \\

Damit ist $f$ auf $\mathbb{R}$ \ {1} stetig.

** b)
- Punkte an Intevallgrenzen (P_1(-1, -1) und P_2(2, ln(2)))
- einsetzten in $s(x) = y_1 + \frac{y_2 - y_1}{x_2 - x_1}x$

* Aufgabe 3
** a)
- Intevallgrenzen einsetzten in f
- f ist stetig und differenzierbar
- Folgerung: Nullstelle

** b)
* Aufgabe 4
** a)
** b)
*** (a)
$$ (5x^3 - 2\sin(3x))' = 15x^2 - 6\cos(3x) $$

*** (b)
$$ (\cos(x) e^x)' = \cos(x)e^x - \sin(x)e^x $$

*** (c)
$$ (e^{2x^2+11} + 7)' = 4x e^{2x^2+11} $$

*** (d)
$$ \left( \frac{\sin(x^2 - 2\pi)}{\cos(3\pi - x^2)} \right)' = \frac{-2x}{\cos^2(3\pi - x^2)} $$

* Aufgabe 5
Für die 1. Ableitung von $f$ gilt

$$ f'(x) = -\frac{2}{(x-2)^2} $$

dann gilt für eine beliebige Tangente $t(x) = ax + b$ am Graphen von $f$

\begin{align*}
  a &= f'(x_0) = -\frac{2}{(x_0-2)^2} \\
  b &= f(x_0) - f'(x_0) \cdot x_0 = \frac{2}{x_0-2} + 2 + \frac{2 x_0}{(x_0-2)^2}
\end{align*}

mit der Anforderung, dass $a = -\frac{1}{2}$ sein muss. Damit gilt

\begin{align*}
  a = -\frac{2}{(x_0-2)^2} &= -\frac{1}{2} \\
  \Leftrightarrow \frac{(x_0-2)^2}{2} &= 2 \\
  \Leftrightarrow (x_0-2)^2 &= 4 \\
  \Leftarrow x_0 - 2 &= \pm 2
\end{align*}

daraus ergeben sich die beiden Stellen $x_1 = 0$ und $x_2 = 4$. Daraus folgen dann die beiden Tangenten

\begin{align*}
  t_1(x) &= -\frac{1}{2}x + 1 \\
  t_2(x) &= -\frac{1}{2}x + 5
\end{align*}

\begin{tikzpicture}
  \begin{axis}[xlabel = $x$, ylabel = {$f(x)$}, ymin=-3, ymax=9]
  \addplot[samples=100, color=black, domain=-2:1.99]{2/(x-2) + 2};
  \addplot[samples=100, color=black, domain=2.01:6]{2/(x-2) + 2};
  \addlegendentry{$f$}
  \addlegendentry{$f$}
  \addplot[color=blue, domain=-2:6]{-1/2 * x + 1};
  \addlegendentry{$t_1$}
  \addplot[color=green, domain=-2:6]{-1/2 * x + 5};
  \addlegendentry{$t_2$}
  \end{axis}
\end{tikzpicture}

* Aufgabe 6
** a)
** b)
