
#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 03 - Al-Maweri 13
#+AUTHOR: Daniel Geinets (453843), Christopher Neumann (409098), Dennis Schulze (458415)

#+LATEX_CLASS_OPTIONS: [a4paper, 11pt]

#+LATEX_HEADER: \usepackage{braket}
#+LATEX_HEADER: \usepackage[AUTO]{babel}

#+LANGUAGE: de

#+LATEX: \setcounter{secnumdepth}{0}
#+LATEX: \newcommand{\tuple}[1]{\left(#1\right)}
#+LATEX: \renewcommand{\cfrac}[3]{#1 \tuple{\frac{#2}{#3}}}
#+LATEX: \newcommand{\R}{\mathbb{R}}
#+LATEX: \newcommand{\Z}{\mathbb{Z}}
#+LATEX: \newcommand{\Q}{\mathbb{Q}}
#+LATEX: \newcommand{\N}{\mathbb{N}}
#+LATEX: \newcommand{\C}{\mathbb{C}}

\pagebreak

* Aufgabe 1
** a)
*** i)
$$ z^3 = -27i = 27 e^{-\frac{\pi}{2}i} $$

Es gilt für den Betrag $r$ und das Argument $\phi_n$ mit $n \in \set{0, 1, 2}$
von $z$

\begin{align*}
    r &= \sqrt[3]{27} = 3 \\
    \phi_n &= -\frac{\pi}{2 \cdot 3} + \frac{2n\pi}{3} \\
    &= \frac{-\pi + 4n \pi}{6} = \frac{\pi(4n - 1)}{6}
\end{align*}

Dann gilt

$$ z = 3 e^{\frac{\pi(4n - 1)}{6}i} \text{ mit } n = 0, 1, 2 $$

*** ii)
$$ 2z^4 + 4(\sqrt{12} - 2i)z^2 + 16 - 8\sqrt{12}i = 0 $$

Es gilt für den ersten Koeffizienten mit $r, \phi \in \R$

\begin{align*}
    r &= \sqrt{12 + (-2)^2} = 4 \\
    \tan(\phi) &= \frac{-2}{\sqrt{12}} = \frac{-1}{\sqrt{3}} \\
    &= \frac{-1}{\sqrt{3}} \\
    \Leftrightarrow \phi &= \arctan \tuple{\frac{-1}{\sqrt{3}}} = -\frac{\pi}{6}
\end{align*}

damit gilt

$$ \sqrt{12} - 2i = 4 e^{-\frac{\pi}{6}i} $$

analog gilt dann für den zweiten Koeffizienten

$$ 16 - 8\sqrt{12}i = 32 e^{-\frac{\pi}{3}i} $$

\pagebreak

dann gilt

\begin{align*}
    2z^4 + 4(\sqrt{12} - 2i)z^2 + 16 - 8\sqrt{12}i &= 0 \\
    \Leftrightarrow 2z^4 + 16 e^{-\frac{\pi}{6}i}z^2 + 32 e^{-\frac{\pi}{3}i} &= 0 \\
    \Leftrightarrow z^4 + 8 e^{-\frac{\pi}{6}i}z^2 + 16 e^{-\frac{\pi}{3}i} &= 0 \\
    \Leftrightarrow (z^2 + 4 e^{-\frac{\pi}{6}i})^2 &= 0 \\
\end{align*}

daraus folgt dann die Gleichung

$$ z^2 = -4 e^{-\frac{\pi}{6}i} = 4 e^{\frac{5\pi}{6}i} $$

für $z$ gilt dann mit $s, \phi_k \in \R$

\begin{align*}
    s &= \sqrt{4} = 2 \\
    \phi_k &= \tuple{\frac{5 \pi}{6} + 2k\pi} \frac{1}{2} \text{ mit } k = 0, 1 \\
    &= \tuple{\frac{5 \pi}{6} + \frac{12k\pi}{6}} \frac{1}{2}
    = \tuple{\frac{\pi (5 + 12k)}{6}} \frac{1}{2} \\
    &= \frac{\pi (5 + 12k)}{12}
\end{align*}

damit gilt

$$ z = 2 e^{\frac{\pi (5 + 12k)}{12}i} \text{ mit } k = 0, 1 $$

*_NOTE:_* In diesem Fall sind das beides doppelte Nullstellen.

** b)
Es gilt

\begin{align*}
    i e^{\frac{5\pi}{12}i} &= i e^{\frac{2\pi + 3\pi}{4 \cdot 3}i} \\
    &= i e^{\frac{\pi}{4}i + \frac{\pi}{6}i} \\
    &= i e^{\frac{\pi}{4}i} e^{\frac{\pi}{6}i} \\
    &= i \tuple{\cfrac{\cos}{\pi}{4} + i\cfrac{\sin}{\pi}{4}}
        \tuple{\cfrac{\cos}{\pi}{6} + i\cfrac{\sin}{\pi}{6}} \\
    &= i \tuple{\cfrac{\cos}{\pi}{4}\cfrac{\cos}{\pi}{6} + i \cfrac{\cos}{\pi}{4}\cfrac{\sin}{\pi}{6}
        +i \cfrac{\sin}{\pi}{4}\cfrac{\cos}{\pi}{6} - \cfrac{\sin}{\pi}{4}\cfrac{\sin}{\pi}{6}} \\
    &= i \tuple{\frac{\sqrt{3}}{2\sqrt{2}} + \frac{1}{2\sqrt{2}}i +
        \frac{\sqrt{3}}{2\sqrt{2}}i - \frac{1}{2\sqrt{2}}} \\
    &= \frac{-1 - \sqrt{3}}{2\sqrt{2}} + \frac{\sqrt{3} - 1}{2\sqrt{2}}i
\end{align*}

* Aufgabe 2
** a)
$$ p(i) = (i)^4 - 1 = 1 - 1 = 0 $$

** b)
Polynomdivision:

\begin{align*}
    (z^4 - 1) / (z^2 + 1) &= \\
    (-z^2 - 1) / (z^2 + 1) &= z^2 \\
    (0) / (z^2 + 1) &= z^2 - 1
\end{align*}

demnach gilt

$$ \frac{p(z)}{q(z)} = z^2 - 1 $$

** c)
$p$ lässt sich im Komplexen wie folgt zerlegen

\begin{align*}
    p(z) = z^4 - 1 &= (z^2 + 1)(z^2 - 1) \\
    &= (z^2 + 1)(z + 1)(z - 1) \\
    &= (z + i)(z - i)(z + 1)(z - 1) \\
\end{align*}

** d)
$p$ lässt sich im Reellen wie folgt zerlegen

$$ p(z) = z^4 - 1 = (z^2 + 1)(z + 1)(z - 1) $$

\pagebreak

* Aufgabe 3
** a)
Für den Nenner $p$ gilt

\begin{align*}
    p(x) &= x^2 - 2x + 5 \\
    &= (x - (1 + 2i))(x - (1 - 2i))
\end{align*}

damit gilt für die Zerlegung

$$ \frac{x}{x^2 - 2x + 5} = \frac{A}{x - (1 + 2i)} + \frac{B}{x - (1 - 2i)} $$

** b)
Es gilt

\begin{align*}
    \frac{i}{x - (1 + 2i)} + \frac{-i}{x - (1 - 2i)} &=
       \frac{i(x - 1 + \sqrt{2}i) - i(x - 1 - \sqrt{2}i)}{x^2 - 2x + 5} \\
    &= \frac{-2\sqrt{2}}{x^2 - 2x + 5}
\end{align*}

damit gilt für die reelle Zerlegung

$$ f(x) = \frac{-2\sqrt{2}}{x^2 - 2x + 5} $$

* Aufgabe 4
** a)
Sei $p$ das Zahlerpolynom und $q$ das Nennerpolynom.

Für den $p$ gilt

$$ p(x) = x^2 - 6x + 9 = (x - 3)^2 $$

Es muss eine Polynomdivision durchgeführt werden, da gilt $\deg(p) > \deg(q)$.
Es folgt eine Polynomdivision:

\begin{align*}
    (x^3 - 6x^2 + 10x - 1) / (x^2 - 6x + 9) &= \\
    (x - 1) / (x^2 - 6x + 9) &= x 
\end{align*}

\pagebreak

damit gilt

$$ \frac{p(x)}{q(x)} = x + \frac{x - 1}{(x - 3)^2} $$

daraus ergibt sich der komplexe Ansatz der Zerlegung mit $A, B \in \C$

$$ \frac{x - 1}{(x - 3)^2} = \frac{A}{x - 3} + \frac{B}{(x - 3)^2} $$

damit gilt für $B$ mit $x = 3$

$$ (3) - 1 = 2 = B $$

und für $A$ gilt

$$ x - 1 = Ax - 3A + 2 \Leftrightarrow x - 1 = Ax - 3A + 2 $$

daraus ergeben sich

\begin{align*}
    1 &= A \\
    -1 &= -3A + 2 \\
    \\
    \Rightarrow A &= 1
\end{align*}

Da $A$ und $B$ Elemente der reellen und komplexen Zahlen sind, ist die folgende Zerlegung
sowohl reel als auch komplex

$$ \frac{p(x)}{q(x)} = x + \frac{1}{x - 3} + \frac{2}{(x - 3)^2} $$

** b)
Sei $p$ das Zahlerpolynom und $q$ das Nennerpolynom.

Da $\deg(p) < \deg(q)$ gilt, muss keine Polynomdivision durchgeführt werden. \\
Für $q$ gilt


\begin{align*}
    q(x) = x^3 + 2x = x(x^2 + 2) = x(x + \sqrt{2}i)(x - \sqrt{2}i)
\end{align*}

daraus ergibt sich dann folgender Ansatz mit $A, B, C \in \C$

$$ \frac{2x^2 - 2x - 1}{x(x + \sqrt{2}i)(x - \sqrt{2}i)} = \frac{A}{x} +
    \frac{B}{x + \sqrt{2}i} + \frac{C}{x - \sqrt{2}i} $$

\pagebreak
    
damit gilt für $A$ mit $x = 0$

$$ \frac{-1}{2} = A $$

und es gilt für $B$ mit $x = -\sqrt{2}i$

$$ \frac{-4 + 2\sqrt{2}i - 1}{(-\sqrt{2}i)(-2\sqrt{2}i)} = B = \frac{5 - 2\sqrt{2}i}{4} $$

und es gilt für $C$ mit $x = \sqrt{2}i$

$$ \frac{-4 - 2\sqrt{2}i - 1}{(\sqrt{2}i)(2\sqrt{2}i)} = C = \frac{5 + 2\sqrt{2}i}{4} $$

damit gilt für die komplexe Zerlegung

$$ \frac{p(x)}{q(x)} = \frac{\frac{-1}{2}}{x} + \frac{\frac{5 - 2\sqrt{2}i}{4}}{x + \sqrt{2}i} +
    \frac{\frac{5 + 2\sqrt{2}i}{4}}{x - \sqrt{2}i} $$

es gilt

\begin{align*}
    \frac{\frac{5 - 2\sqrt{2}i}{4}}{x + \sqrt{2}i} + \frac{\frac{5 + 2\sqrt{2}i}{4}}{x - \sqrt{2}i} &=
        \frac{\frac{1}{4}((5 - 2\sqrt{2}i)(x - \sqrt{2}i) + (5 + 2\sqrt{2}i)(x + \sqrt{2}i))}{x^2 + 2} \\
    &= \frac{\frac{1}{4}(5x - 5\sqrt{2}i - 2\sqrt{2}xi - 4 + 5x + 5\sqrt{2}i + 2\sqrt{2}xi - 4)}{x^2 + 2} \\
    &= \frac{\frac{1}{2}(5x - 4)}{x^2 + 2}
\end{align*}

damit gilt für die reelle Zerlegung

$$ \frac{p(x)}{q(x)} = \frac{\frac{-1}{2}}{x} + \frac{\frac{1}{2}(5x - 4)}{x^2 + 2} $$
