
#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 02 - Al-Maweri 13
#+AUTHOR: Daniel Geinets (453843), Christopher Neumann (409098), Dennis Schulze (458415)

#+LATEX_CLASS_OPTIONS: [a4paper, 11pt]

#+LATEX_HEADER: \usepackage{braket}
#+LATEX_HEADER: \usepackage[AUTO]{babel}

#+LANGUAGE: de

#+LATEX: \setcounter{secnumdepth}{0}
#+LATEX: \newcommand{\tuple}[1]{\left(#1\right)}
#+LATEX: \newcommand{\R}{\mathbb{R}}
#+LATEX: \newcommand{\Z}{\mathbb{Z}}
#+LATEX: \newcommand{\Q}{\mathbb{Q}}
#+LATEX: \newcommand{\N}{\mathbb{N}}
#+LATEX: \newcommand{\C}{\mathbb{C}}

\pagebreak

* Aufgabe 1
** a)
Zu zeigen ist
$$ \forall n \in \N, n \geq 1, \sum_{k=1}^{n} \tuple{2k - 1} = n^2 $$

IA:
    Es gilt für $n = 1$

$$ \sum_{k=1}^{1} \tuple{2k - 1} = (2(1) - 1) = 1 = (1)^2 $$

IB:
    Es gelte für ein beliebiges $n \in \N$ mit $n \geq 1$

$$ \sum_{k=1}^{n} \tuple{2k - 1} = n^2 $$

IV:
    Damit gilt dann

$$ \sum_{k=1}^{n+1} \tuple{2k - 1} = (n + 1)^2 $$

IS:
    Es gilt

\begin{align*}
    \sum_{k=1}^{n+1} \tuple{2k - 1} &= \sum_{k=1}^{n} \tuple{2k - 1} + 2(n + 1) - 1 \\
    &= n^2 + 2(n + 1) - 1 = n^2 + 2n + 1 = (n + 1)^2
\end{align*}

Folglich gilt dann für alle $n \in \N$ mit $n \geq 1$

$$ \sum_{k=1}^{n} \tuple{2k - 1} = n^2 $$
    
** b)
$$ \prod_{k=2}^{n} \tuple{1 - \frac{1}{k^2}} = \frac{n + 1}{2n}, n \in \N, n \geq 2 $$

IA:
  Es gilt

\begin{align*}
    \prod_{k = 2}^{2} \tuple{1 - \frac{1}{k^2}} = \frac{2 + 1}{4}
    = \frac{3}{4}
    = 1 - \frac{1}{4}
\end{align*}

IB:
  Es gelte für ein beliebiges n \in $\N$ mit n > 1
$$ \prod_{k=2}^{n} \tuple{1 - \frac{1}{k^2}} = \frac{n + 1}{2n} $$

IV:
  Dann gilt
$$ \prod_{k=2}^{n + 1} \tuple{1 - \frac{1}{k^2}} = \frac{n + 2}{2(n + 1)} $$

IS:
  Es gilt

\begin{align*}
    \prod_{k = 2}^{n + 1} \tuple{1 - \frac{1}{k^2}} &= \prod_{k = 2}^{n} \tuple{1 - \frac{1}{k^2}} \cdot \tuple{1 - \frac{1}{(n + 1)^2}} \\
    &= \frac{n + 1}{2n} \cdot \tuple{1 - \frac{1}{(n + 1)^2}} \\
    &= \frac{n + 1}{2n} \cdot \tuple{\frac{(n+1)^2}{(n+1)^2} - \frac{1}{(n + 1)^2}} \\
    &= \frac{n + 1}{2n} \cdot \frac{(n+1)^2 - 1}{(n+1)^2} \\
    &= \frac{n + 1}{2n} \cdot \frac{((n+1) - 1)((n+1) + 1)}{(n + 1)^2} \\
    &= \frac{n + 1}{2n} \cdot \frac{n(n + 2)}{(n + 1)(n + 1)} \\
    &= \frac{(n + 1) \cdot n(n + 2)}{2n(n + 1)(n + 1)}
    = \frac{n + 2}{2(n + 1)}
\end{align*}


Damit gilt für alle n \in $\N$ mit n > 1
$$ \prod_{k=2}^{n} \tuple{1 - \frac{1}{k^2}} = \frac{n + 1}{2n} $$

** c)
$$ \forall n \in \N, n \geq 4, \text{ gilt } 2^n \geq n^2 $$

IA:
  Es gilt für n = 4

\begin{align*}
    2^4 &\geq 4^2 \\
    \Leftrightarrow 16 &\geq 16
\end{align*}

IV:
  Es gelte für ein beliebiges $n \in \N$ mit n \geq 4
$$ 2^n \geq n^2 $$

IB:
  Dann gilt
$$ 2^{n + 1} \geq (n + 1)^2 $$

IS:
  Es gilt

\begin{align*}
    2^{n + 1} &\geq (n + 1)^2 \\
    \Leftrightarrow 2 \cdot 2^n &\geq 2 \cdot n^2 = n^2 + 2n + 1 \\
    \Rightarrow n^2 &= 2n + 1 \\
    \Leftrightarrow 0 &= n^2 - 2n - 1 \\
    \Rightarrow n_1 &= 1 - \sqrt{2} \text{ und } n_2 = 1 + \sqrt{2}, n_i \in \R \\
    \Rightarrow n_1 &< 4 \text{ und } n_2 < 4 \text{ (siehe IV.)} \\
    \Rightarrow n^2 &> 2n + 1 \\
    \Rightarrow 2 \cdot n^2 &> n^2 + 2n + 1 = (n + 1)^2 \\
    \Rightarrow 2 \cdot 2^n &> (n + 1)^2 \\
    \Leftrightarrow 2^{n + 1} &> (n + 1)^2
\end{align*}


Damit gilt für alle $n \in \N$ mit n \geq 4
$$ 2^n \geq n^2 $$

Für $n = 0, 1, 2, 3$ gilt jewals

\begin{align*}
    2^0 &> (0)^2 \Leftrightarrow 1 > 0 \\
    2^1 &> (1)^2 \Leftrightarrow 2 > 1 \\
    2^2 &= (2)^2 \Leftrightarrow 4 = 4 \\
    2^3 &< (3)^2 \Leftrightarrow 8 < 9
\end{align*}

* Aufgabe 2
** a)
$f$ ist streng monoton fallend \\
\Rightarrow $f$ ist injektiv \\
\\
$\exp$ nur injektiv auf $\R$, ($\exp : \R \rightarrow ]0, \infty[, x \mapsto e^x$)\\
\Rightarrow $f$ ist nur injektiv

** b)
Da gilt $|-x|^5 = |x|^5$, folgt daraus, dass $g$ nicht injektiv ist. \\
Des weiteren ist $g$ nach unten beschränkt ($g(x) \geq 0$ für alle $x \in \R$), daraus folgt,
dass $g$ nicht surjektiv. \\
Damit ist $g$ weder injektiv noch surjektiv.

* Aufgabe 3
** a)
\begin{align*}
    D_{f_3} &= \R \setminus \set{x \in \R | \cos(x) \neq 0} \\
    &= \R \setminus \left\{ \frac{\pi}{2} + k\pi \text{ | } k \in \Z \right\}
\end{align*}

** b)
\begin{align*}
    (f_1 \circ f_2)(x) &= \tuple{\frac{1}{x^3}}^2 - 4 \\
    &= \frac{1}{x^6} - 4
\end{align*}

$$ D_{f_1 \circ f_2} = \R \setminus \{0\} $$

\begin{align*}
    (f_2 \circ f_1)(x) &= \frac{1}{(x^2 - 4)^3} \\
    &= \frac{1}{((x - 2)(x + 2))^3}
\end{align*}

$$ D_{f_2 \circ f_1} = \R \setminus \{-2, 2\} $$

** c)
$$ f_{1}^{-1}([0, 12]) = [2, 4] $$

** d)
Behauptung 1: $f_1$ ist gerade \\
\\
Zu zeigen ist: $f_1(-x) = f_1(x)$ \\
Es gilt

\begin{align*}
    f_1(-x) &= (-x)^2 - 4 \\
    &= (-1)^2 x^2 - 4 \\
    &= x^2 - 4 = f_1(x)
\end{align*}

Damit ist $f_1$ gerade. \\
\\
\\
Behauptung 2: $f_3$ ist gerade \\
\\
Zu zeigen ist: $f_3(-x) = f_3(x)$ \\
Es gilt

\begin{align*}
    f_3(-x) &= \frac{\sin((-x)^2)}{\cos(-x)} \\
    &= \frac{\sin((-1)^2 x^2)}{\cos(x)} \\
    &= \frac{\sin(x^2)}{\cos(x)} = f_3(x) \\
\end{align*}

Damit ist auch $f_3$ gerade.

* Aufgabe 4
** a)
Es gilt

\begin{align*}
    y &= \frac{x+3}{x+1} \\
    \Leftrightarrow y(x+1) &= x+3 \\
    \Leftrightarrow yx+y &= x+3 \\
    \Leftrightarrow (y-1)x+y &= 3 \\
    \Leftrightarrow x &= \frac{3-y}{y-1}, y \neq 1 \\
\end{align*}

Damit gilt

$$ f^{-1}(y) = \frac{3-y}{y-1} $$
$$ D_{f^{-1}} = \R \setminus \{1\} $$

** b)
\begin{align*}
    (f \circ f^{-1})(y) &= \frac{\tuple{\frac{3-y}{y-1}}+3}{\tuple{\frac{3-y}{y-1}}+1} \\
    &= \frac{\tuple{\frac{3-y + 3y-3}{y-1}}}{\tuple{\frac{3-y + y-1}{y-1}}} \\
    &= \frac{\frac{2y}{y-1}}{\frac{2}{y-1}} \\
    &= \frac{2y}{y-1} \cdot \frac{y-1}{2} \\
    &= y \\
\end{align*}

** c)
Behauptung: $f$ ist auf $]-1, \infty[$ monoton fallend \\
\\
Zu zeigen ist $f(x_1) > f(x_2)$ für $x_1, x_2 \in ]-1, \infty[$ mit $x_1 < x_2$ \\

Es gelte $f(x_1) > f(x_2)$ für $x_1, x_2 \in ]-1, \infty[$

dann gilt

\begin{align*}
    \frac{x_1 + 3}{x_1 + 1} &> \frac{x_2 + 3}{x_2 + 1} \\
    \Leftrightarrow (x_1 + 3)(x_2 + 1) &> (x_2 + 3)(x_1 + 1) \\
    \Leftrightarrow x_1 x_2 + x_1 + 3 x_2 + 3 &> x_1 x_2 + x_2 + 3 x_1 + 3 \\
    \Leftrightarrow x_1 + 3 x_2 &> x_2 + 3 x_1 \\
    \Leftrightarrow 2 x_2 &> 2 x_1 \\
    \Leftrightarrow x_2 &> x_1 \Leftrightarrow x_1 < x_2 \\
\end{align*}

da gilt $x_1 < x_2$ und es gilt $f(x_1) > f(x_2)$, woraus folgt, \\
dass $f$ auf $]-1, \infty[$ monoton fallend ist.
