
#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 03 - Geuter 29
#+AUTHOR: Moaz Haque, Felix Oechelhaeuser, Leo Pirker, Dennis Schulze

* Aufgabe 1
** a)
\begin{equation*}
\begin{aligned}
p(z) &= z^2 + 3z - 1 + 2i \\
 &= (z^2 - 2z) + (5z - 5) + (4 + 2i) \\
 &= 2 T_2(z) + 5 T_1(z) + (4 + 2i) T_0(z)
\end{aligned}
\end{equation*}

** b)
\begin{equation*}
\begin{aligned}
\sin\left( x + \frac{\pi}{3} \right) &= 
  \sin(x) \cos\left( \frac{\pi}{3}\right) + \cos(x) \sin\left( \frac{\pi}{3} \right) \\
 &= \sin(x) \frac{1}{2} + \cos(x) \frac{ \sqrt{3} }{2}
\end{aligned}
\end{equation*}

* Aufgabe 2
** a)
Umformung der Regel von $T_1$:

\begin{equation*}
\begin{aligned}
0 &= 3x_1 - 2x_2 \\
\Leftrightarrow 2x_2 &= 3x_1 \\
\Leftrightarrow x_2 &= \frac{3}{2}x_1
\end{aligned}
\end{equation*}

Damit gilt für $T_1$:

\begin{equation*}
\begin{aligned}
T_1 &= \left\{ \begin{bmatrix} x_1 \\ \frac{3}{2}x_1 \end{bmatrix} \in \mathbb{R}^2 \right\} \\
 &= \text{span}\left\{ \begin{bmatrix} 1 \\ \frac{3}{2} \end{bmatrix} \right\}
\end{aligned}
\end{equation*}

Damit gelten die Addition und Skalarmultiplikation in $T_1$. Und daraus folgt:

$$T_1 \subset \mathbb{R}^2$$

Umformung der Regel von $T_2$:

\begin{equation*}
\begin{aligned}
1 &= x_1 x_2^3 \\
\Leftrightarrow \frac{1}{x_1} &= x_2^3 \\
\Leftrightarrow \frac{1}{\sqrt[3]{x_1}} &= x_2
\end{aligned}
\end{equation*}

Damit gilt für $T_2$:

$$T_2 = \left\{ \begin{bmatrix} x_1 \\ \frac{1}{\sqrt[3]{x_1}} \end{bmatrix} \in \mathbb{R}^2 \right\}$$

Daraus folgt, dass keiner der Vektoren in $T_2$ als vielfaches eines anderen Vektors aus $T_2$ dargestellt werden kann.
Ebenso gibt es keine zwei Vektoren $v, w \in T_2, v \neq -w$ für die gilt $v + w \in T_2$.

Daraus folgt:

$$T_2 \not\subset \mathbb{R}^2$$

** b)
$\forall f, g \in T$ gilt $f + g \in T$, da alle $f$ und $g$ an der Stelle $x = -2$ eine Nullstelle besitzen 
und $f + g$ muss dem zu folge ebenfalls bei $x = -2$ eine Nullstelle besitzen.
Analog gilt auch $\forall f \in T$ mit $\lambda \in \mathbb{R}$, dass $\lambda f \in T$. Auch hier hat $f$ eine Nullstelle bei $x = -2$,
die bei $\lambda f$ erhalten bleibt.

Also gilt:

$$T \subset V$$

* Aufgabe 3
** a
Ansatz zum überprüfen auf lineare Abhänigkeit:

\begin{equation*}
\begin{aligned}
0 &= a_0 \begin{bmatrix} 3 \\ 0 \\ 2  \end{bmatrix} +
     a_1 \begin{bmatrix} -3 \\ 5 \\ 3 \end{bmatrix} +
     a_2 \begin{bmatrix} 0 \\ 1 \\ -1 \end{bmatrix} \\
 &= \begin{bmatrix} 3 a_0 \\ 0 \\ 2 a_0 \end{bmatrix} +
    \begin{bmatrix} -3 a_1 \\ 5 a_1 \\ 3 a_1 \end{bmatrix} +
    \begin{bmatrix} 0 \\ a_2 \\ -a_2 \end{bmatrix} \\
 &= \begin{bmatrix} 3 (a_0 - a_1) \\ 5 a_1 + a_2 \\ 2 a_0 + 3 a_1 - a_2 \end{bmatrix}
\end{aligned}
\end{equation*}

Daraus folgt $a_0 = a_1$ aus der ersten Komponente, $5a_1 = -a_2$ aus der zweiten Komponente.
Die Folgerung aus der dritte Komponente steht im widerspruch zu den ersten beiden,
da diese immer ungleich 0 ist, wenn die ersten beiden Komponenten gleich 0 sind.

Damit gilt nur die triviale Lösung $a_0 = a_1 = a_2 = 0$ und damit sind die Vektoren linear unabhängig.

** b
Ansatz zum überprüfen auf lineare Abhänigkeit:

\begin{equation*}
\begin{aligned}
0 &= a_1 p_1(z) + a_2 p_2(z) + a_3 p_3(z) + a_4 p_4(z) \\
 &=  a_1 + a_2 (3z - 1) + a_3 (z^2 - 1) + a_4 (2z^3 - 3z^2) \\
 &=  a_1 + 3 a_2 z - a_2 + a_3 z^2 - a_3 + 2 a_4 z^3 - 3 a_4 z^2 \\
 &= (a_1 - a_2 - a_3) + 3 a_2 z + (a_3 - 3 a_4) z^2 + 2 a_4 z^3
\end{aligned}
\end{equation*}

Daraus ergeben sich durch Koeffizientenvergleich die Gleichungen:

\begin{equation*}
\begin{aligned}
\text{(I) } 0 &= a_1 - a_2 - a_3 \\
\text{(II) } 0 &= 3 a_2 \\
\text{(III) } 0 &= a_3 - 3 a_4 \\
\text{(IV) } 0 &= 2 a_4
\end{aligned}
\end{equation*}

Aus II und IV folgen jewals $a_2 = a_4 = 0$. Damit folgt aus III $a_3 = 0$. Und schließlich folgt dann aus I $a_1 = 0$.

Damit ist die triviale Lösung $a_1 = a_2 = a_3 = a_4 = 0$ die einzige Lösung und damit sind die Polynome/Vektoren linear unabhängig.

** c
* Aufgabe 4
** a
** b
** c
* Aufgabe 5
** a
** b
* Aufgabe 6
** a
** b
