
#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 06 - Geuter 29
#+AUTHOR: Moaz Haque, Felix Oechelhaeuser, Leo Pirker, Dennis Schulze

* Aufgabe 1
** a)
** b)
** c)
** d)

* Aufgabe 2
** a)
Da $f$ eine lineare Abbildung ist, gelten

$$f(x + y) = f(x) + f(y) \text{ und } f(\lambda x) = \lambda f(x)$$

und damit gilt

\begin{equation*}
\begin{aligned}
f(4x) &= 2 f(2x + 3) - 3 f(2) \\
 &= 2(-x + 1) - 3(3x + 2) \\
 &= -2x + 2 - 9x - 6 \\
 &= -11x - 4
\end{aligned}
\end{equation*}

** b)
Ansatz für $\text{Bild}(f)$:

\begin{equation*}
\begin{aligned}
  f(x) &= \frac{1}{4} f(4x) = \frac{-11}{4}x - 1 \\
  f(1) &= \frac{1}{2} f(2) = \frac{3}{2}x + 1
\end{aligned}
\end{equation*}

Prüfe, ob $f(x)$ und $f(1)$ linear abhängig sind:

Seien a_1, a_2 \in $\mathbb{R}$ damit gelte

\begin{equation*}
\begin{aligned}
 0 &= a_1 f(1) + a_2 f(x) \\
 &= a_1 (\frac{3}{2}x + 1) + a_2 (\frac{-11}{4}x - 1) \\
 &= \frac{3 a_1}{2}x + a_1 + \frac{-11 a_2}{4}x - a_2 \\
 &= a_1 - a_2 + \frac{6 a_1 - 11 a_2}{4}x
\end{aligned}
\end{equation*}

Durch Koeffizientenvergleich ergeben sich die Gleichungen

\begin{equation*}
\begin{aligned}
\text{(I)  } 0 &= a_1 - a_2 \\
\text{(II)  } 0 &= \frac{1}{4}(6 a_1 - 11 a_2) \\
  \Leftrightarrow 0 &= 6 a_1 - 11 a_2
\end{aligned}
\end{equation*}
 
wo aus I folgt $a_1 = a_2$ und aus II folgt $a_1 = \frac{11}{6} a_2$, was I widersprechen würde,
wenn gilt $a_1 \neq 0 \neq a_2$. Daruas folgt $a_1 = a_2 = 0$ und damit sind $f(x)$ und $f(1)$
linear unabhängig.

Damit gilt $\text{Bild}(f) = \text{span}\{f(1), f(x)\}$, woraus folgt $\dim(\text{Bild}(f)) = 2$.

** c)
Es gelten $\dim(\text{Bild}(f)) = 2$ und $\dim(\mathbb{R}[x]_{\leq 1}) = 2$. \\
Damit ergibt sich aus der Dimensionsformel

\begin{equation*}
\begin{aligned}
 \dim(\mathbb{R}[x]_{\leq 1}) &= \dim(\text{Kern}(f)) + \dim(\text{Bild}(f)) \\
\Leftrightarrow \dim(\text{Kern}(f)) &= \dim(\mathbb{R}[x]_{\leq 1}) - \dim(\text{Bild}(f)) = 2 - 2 = 0
\end{aligned}
\end{equation*}

Damit gilt für die Basis $B_K$ vom Kern($f$)

$$ B_K = \{ \} $$

** d)
Bestimmen von $K_{B_1}$ mit a, b, \lambda_1, \lambda_2 \in $\mathbb{R}$:

\begin{equation*}
\begin{aligned}
ax + b \mapsto \begin{bmatrix} \lambda_1 \\ \lambda_2 \end{bmatrix} \\
\text{mit  } \lambda_1 (2x + 3) + \lambda_2 2 &= ax + b \\
  2\lambda_1 x + \lambda_1 3 + \lambda_2 2 &= ax + b
\end{aligned}
\end{equation*}

Durch Koeffizientenvergleich ergibt sich:

\begin{equation*}
\begin{aligned}
\text{(I)  } a &= 2\lambda_1 \\ 
\text{(II)  } b &= \lambda_1 3 + \lambda_2 2
\end{aligned}
\end{equation*}

Daraus ergeben sich einmal nach I $\lambda_1 = \frac{a}{2}$ \\
und anschließend nach II $\lambda_2 = \frac{2b - 3a}{4}$.

Daraus folgt

$$K_{B_1}: ax + b \mapsto \begin{bmatrix} \frac{a}{2} \\ \frac{2b - 3a}{4} \end{bmatrix}$$


Bestimmen von $K_{B_2}$ mit c, d, \beta_1, \beta_2 \in $\mathbb{R}$:

\begin{equation*}
\begin{aligned}
cx + d \mapsto \begin{bmatrix} \beta_1 \\ \beta_2 \end{bmatrix} \\
\text{mit  } \beta_1 (-x + 1) + \beta_2 (3x + 2) &= cx + d \\
  -\beta_1 x + \beta_1 + 3\beta_2 x + 2\beta_2 &= cx + d \\
   (3\beta_2 - \beta_1)x + \beta_1 + 2\beta_2 &= cx + d
\end{aligned}
\end{equation*}

Durch Koeffizientenvergleich ergibt sich:

\begin{equation*}
\begin{aligned}
  \begin{bmatrix} c \\ d \end{bmatrix} &=
  \begin{bmatrix} -1 & 3 \\ 1 & 2 \end{bmatrix} 
  \begin{bmatrix} \beta_1 \\ \beta_2 \end{bmatrix} \\
e &= A \beta
\end{aligned}
\end{equation*}

was umgeschrieben werden kann zu

\begin{equation*}
\begin{aligned}
  \left[A|e\right] = &\left[ \begin{array}{@{}cc|c@{}}
    -1 & 3 & c \\
    1 & 2 & d
  \end{array} \right] \\
\xrightarrow{\text{II} + \text{I}}
  &\left[ \begin{array}{@{}cc|c@{}}
    -1 & 3 & c \\
    0 & 5 & c+d
  \end{array} \right]
\xrightarrow{-\text{I}}
  \left[ \begin{array}{@{}cc|c@{}}
    1 & -3 & -c \\
    0 & 5 & c+d
  \end{array} \right] \\
\xrightarrow{5\text{I} + 3\text{II}}
  &\left[ \begin{array}{@{}cc|c@{}}
    5 & 0 & -2c+3d \\
    0 & 15 & 3c+3d
  \end{array} \right]
\xrightarrow{\frac{1}{5}\text{I}, \frac{1}{15}\text{II}}
  \left[ \begin{array}{@{}cc|c@{}}
    1 & 0 & \frac{-2c+3d}{5} \\
    0 & 1 & \frac{c+d}{5}
  \end{array} \right]
\end{aligned}
\end{equation*}

und daraus folgt $\beta_1 = \frac{-2c+3d}{5}$ und $\beta_2 = \frac{c+d}{5}$.

Damit ergibt sich

$$K_{B_2}: cx + d \mapsto \begin{bmatrix} \frac{-2c+3d}{5} \\ \frac{c+d}{5} \end{bmatrix}$$

Daraus folgt mit b_n \in $B_1$

\begin{equation*}
\begin{aligned}
f_{B_1, B_2}(e_n) &= K_{B_2}(f(K_{B_1}^{-1}(e_n))) \text{ mit } n \in \left\{ 1, 2 \right\} \\
\Leftrightarrow f_{B_1, B_2}(e_n) &= K_{B_2}(f(b_n))
\end{aligned}
\end{equation*}

\pagebreak
Einsetzen der basen:

\begin{equation*}
\begin{aligned}
K_{B_2}(f(b_1)) &= K_{B_2}(f(2x+3)) &= K_{B_2}(-x+1) &= \begin{bmatrix} 1 \\ 0 \end{bmatrix}\\
K_{B_2}(f(b_2)) &= K_{B_2}(f(2)) &= K_{B_2}(3x+2) &= \begin{bmatrix} 0 \\ 1 \end{bmatrix}
\end{aligned}
\end{equation*}

Damit gilt

\begin{equation*}
f_{B_1, B_2} = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
\end{equation*}

* Aufgabe 3
Behautung: \\
Die Zahlenfolgt $(x_n)_n$ konvergiert gegen 0, wenn $n$ gegen \infty strebt. \\
\\
_zu zeigen_: \forall \epsilon > 0 gibt es ein $N_{\epsilon} \in \mathbb{N}$, so dass gilt

$$|x_n - 0| = \left| \frac{2}{n + 1} - 0 \right| < \epsilon, \forall n \geq N_{\epsilon}$$

Es gilt

\begin{equation*}
\begin{aligned}
\left| \frac{2}{n + 1} - 0 \right| &< \epsilon \\
\Leftrightarrow \frac{2}{n + 1} &< \epsilon \\
\Leftrightarrow \frac{2}{\epsilon} &< n + 1 \\
\Leftrightarrow \frac{2}{\epsilon} - 1 &< n
\end{aligned}
\end{equation*}

Man wählt nun ein $N_{\epsilon} \in \mathbb{N}$ mit $N_{\epsilon} > \frac{2}{\epsilon} - 1$.
Dann gilt \forall $n$ \geq $N_{\epsilon}$:

$$\left| \frac{2}{n + 1} - 0 \right| = \frac{2}{n + 1} \leq \frac{2}{N_{\epsilon} + 1} < \epsilon$$

\pagebreak

Als Beispiel:

\begin{equation*}
\begin{aligned}
\epsilon = \frac{1}{100} \Leftrightarrow \frac{1}{\epsilon} &= 100 \\
\Rightarrow N_{\epsilon} &> \frac{2}{\epsilon} - 1 = 199 \\
\Rightarrow N_{\epsilon} &= 200
\end{aligned}
\end{equation*}

* Aufgabe 4
Ansatz für PBZ mit $A$, $B$ \in $\mathbb{R}$:

\begin{equation*}
\frac{3}{(k + 1)(k + 2)} = \frac{A}{k + 1} + \frac{B}{k + 2}
\end{equation*}

Umgeformt nach $A$ mit $k = -1$:

$$ A = \frac{3}{(-1) + 2} = 3 $$


Umgeformt nach $B$ mit $k = -2$:

$$ B = \frac{3}{(-2) + 1} = -3 $$

Dann gilt mit $n \in \mathbb{N}$

\begin{equation*}
\begin{aligned}
\sum_{k=0}^{n} \frac{3}{(k + 1)(k + 2)} &= \sum_{k=0}^{n} \left( \frac{3}{k + 1} + \frac{-3}{k + 2} \right) \\
 &= \sum_{k=0}^{n} \frac{3}{k + 1} - \sum_{k=0}^{n} \frac{3}{k + 2} \\
 &= 3 + \frac{3}{n + 2}
\end{aligned}
\end{equation*}

und nun muss noch gezeigt werden, dass der Term $\frac{3}{n + 2}$ konvergiert.

\pagebreak

_Behautung_:
$$\lim_{n \rightarrow \infty} \frac{3}{n + 2} = 0$$

Sei $\epsilon > 0$ beliebig. \\
Dann gilt

\begin{equation*}
\begin{aligned}
  \left| \frac{3}{n + 2} - 0 \right| &= \frac{3}{n + 2} < \epsilon \\
\Leftrightarrow \frac{3}{\epsilon} &< n + 2 \Leftrightarrow \frac{3}{\epsilon} - 2 < n
\end{aligned}
\end{equation*}

Man wählt nun ein $N_{\epsilon} \in \mathbb{N}$ mit $N_{\epsilon} > \frac{3}{\epsilon} - 2$. \\
Dann gilt

$$ \left| \frac{3}{n + 2} - 0 \right| &= \frac{3}{n + 2} \leq \frac{3}{N_{\epsilon} + 2} < \epsilon $$

und damit gilt

\begin{equation*}
\lim_{n \rightarrow \infty} \left( \sum_{k=0}^{n} \frac{3}{(k + 1)(k + 2)} \right) = 3
\end{equation*}

* Aufgabe 5
** a)
** b)
** c)

* Aufgabe 6
** a)
** b)
** c)
** d)
