
#+TITLE: Analysis I und Lineare Algebra für Ingenieurwissenschaften \large @@latex: \\@@ Hausaufgabe 08 - Geuter 29
#+AUTHOR: Moaz Haque, Felix Oechelhaeuser, Leo Pirker, Dennis Schulze

#+LATEX_CLASS_OPTIONS: [a4paper,11pt]

\pagebreak

* Aufgabe 1
** a)
Da der Grenzwert des Terms bei direktem Einsetzten nicht definiert ist ("$\frac{0}{0}$"),
muss die Regel von de l'Hospital angewand werden. Also gilt

\begin{align*}
  \lim_{x \rightarrow 0} \frac{e^x - 1}{\sin(2x)} &= \lim_{x \rightarrow 0} \frac{e^x}{2\cos(2x)} \\
  &= \frac{\lim_{x \rightarrow 0}  e^x}{\lim_{x \rightarrow 0}  2\cos(2x)} \\
  &= \frac{1}{2}
\end{align*}

Damit existiert dessen Grenzwert.

** b)
Siehe a) \\
Es gilt

\begin{align*}
  \lim_{x \rightarrow 0} \frac{\cos(x) - 1}{x^2} &= \lim_{x \rightarrow 0} \frac{-\sin(x)}{2x)} \\
  &= \lim_{x \rightarrow 0} \frac{-\cos(x)}{2} \\
  &= \frac{\lim_{x \rightarrow 0}  -\cos(x)}{\lim_{x \rightarrow 0} 2} \\
  &= \frac{-1}{2}
\end{align*}

Damit existiert dessen Grenzwert nach zweifacher Anwendung der Regel.
   
* Aufgabe 2
** a)
** b)
** c)
* Aufgabe 3
* Aufgabe 4
* Aufgabe 5
** a)
Es gilt für die Ableitung von $g$

\begin{align*}
  g'(t) &= \left( (s'(t))^2 + (\omega s(t))^2 \right)' \\
   &= ((s'(t))^2)' + ((\omega s(t))^2)' \\
   &= 2 s'(t) s''(t) + 2 (\omega s(t)) (\omega s'(t)) \\
   &= 2 s'(t) s''(t) + 2 \omega^2 s(t) s'(t) \\
   &= 2 s'(t) (s''(t) + \omega^2 s(t))
\end{align*}

Da $s''(t) = -\omega^2 s(t)$ gilt, folgt daraus

\begin{align*}
  g'(t) &= 2 s'(t) ((-\omega^2 s(t)) + \omega^2 s(t)) \\
   &= 2 s'(t) \cdot 0 = 0
\end{align*}

Da $g'(t) \geq 0$ und $g'(t) \leq 0$ mit $t \in \mathbb{R}$ gelten, folgt daraus,
dass $g(t) = c$, mit $c \in \mathbb{R}$ und für alle $t \in \mathbb{R}$. \\
Daraus folgt, dass $(s'(t))^2 + (\omega s(t))^2$ ebenfalls konstant sein muss.
Daraus folgt wiederum, dass $(s'(t))^2$ und $(\omega s(t))^2$ konstant sind.
Daraus folgt dann, dass $\omega s(t)$ konstant ist und damit gilt $s'(t) = 0$ für alle $t \in \mathbb{R}$,
woraus wiederum aus der ursprüngilchen Annahme folgt $s(t) = 0$ für alle $t \in \mathbb{R}$.
Damit gilt dann für auch $g(t) = 0$, für alle $t \in \mathbb{R}$.

** b)
Es gilt für die erste und zweite Ableitung von $h$

\begin{align*}
  h'(t) &= \left( s(t) - s(0)\cos(\omega t) - \frac{s'(0)}{\omega}\sin(\omega t) \right)' \\
   &= s'(t) + s(0)\omega \sin(\omega t) - s'(0) \cos(\omega t) \\
  \\
  h''(t) &= \left( s'(t) + s(0)\omega \sin(\omega t) - s'(0) \cos(\omega t) \right)' \\
   &= s''(t) + s(0)\omega^2 \cos(\omega t) + s'(0)\omega \sin(\omega t) \\
   &= -\omega^2 s(t) + s(0)\omega^2 \cos(\omega t) + s'(0)\omega \sin(\omega t) \\
   &= -\omega^2 \left( s(t) - s(0)\cos(\omega t) - \frac{s'(0)}{\omega}\sin(\omega t) \right) \\
   &= -\omega^2 h(t)
\end{align*}

Was in 5a) gezeigt wurde, kann analog für $h$ gezeigt werden. Damit gilt

\begin{align*}
  h(t) = 0 &= s(t) - s(0)\cos(\omega t) - \frac{s'(0)}{\omega}\sin(\omega t) \\
\Leftrightarrow s(t) &= s(0)\cos(\omega t) + \frac{s'(0)}{\omega}\sin(\omega t)
\end{align*}

was *eine* Lösung der ursprünglichen Differenzialgleichung ist.

* Aufgabe 6
* Aufgabe 7
